        !COMPILER-GENERATED INTERFACE MODULE: Tue Oct 09 13:10:38 2012
        MODULE AGGOUTWSUNIQUEID__genmod
          INTERFACE 
            SUBROUTINE AGGOUTWSUNIQUEID(AGGOUTCONTROL,OUTSYMBOL,        &
     &AGGOUTNUM,AGGOUTVAR,WATERSHEDFILE,WATERSHEDVARID,DIMLEN2,DIMLEN1, &
     &UNIQUEIDNUMBER,AGGOUTVARNUM)
              INTEGER(KIND=4) :: AGGOUTNUM
              CHARACTER(LEN=200) :: AGGOUTCONTROL
              CHARACTER(LEN=200) :: OUTSYMBOL(66)
              CHARACTER(LEN=200) :: AGGOUTVAR(AGGOUTNUM)
              CHARACTER(LEN=200) :: WATERSHEDFILE
              CHARACTER(LEN=200) :: WATERSHEDVARID
              INTEGER(KIND=4) :: DIMLEN2
              INTEGER(KIND=4) :: DIMLEN1
              INTEGER(KIND=4) :: UNIQUEIDNUMBER
              INTEGER(KIND=4) :: AGGOUTVARNUM(AGGOUTNUM)
            END SUBROUTINE AGGOUTWSUNIQUEID
          END INTERFACE 
        END MODULE AGGOUTWSUNIQUEID__genmod
