        !COMPILER-GENERATED INTERFACE MODULE: Mon Oct 08 18:57:06 2012
        MODULE AGGREGATEDOUTNUM__genmod
          INTERFACE 
            SUBROUTINE AGGREGATEDOUTNUM(AGGOUTCONTROL,OUTSYMBOL,        &
     &AGGOUTNUM)
              CHARACTER(LEN=200) :: AGGOUTCONTROL
              CHARACTER(LEN=200) :: OUTSYMBOL(66)
              INTEGER(KIND=4) :: AGGOUTNUM
            END SUBROUTINE AGGREGATEDOUTNUM
          END INTERFACE 
        END MODULE AGGREGATEDOUTNUM__genmod
