        !COMPILER-GENERATED INTERFACE MODULE: Mon Oct 08 18:57:05 2012
        MODULE INPUTMAXNCFILES__genmod
          INTERFACE 
            SUBROUTINE INPUTMAXNCFILES(INPUTCON,MAXNUMOFFILE,           &
     &INPUTVARNAME,UTCOFFSET)
              CHARACTER(LEN=200) :: INPUTCON
              INTEGER(KIND=4) :: MAXNUMOFFILE
              CHARACTER(LEN=200) :: INPUTVARNAME(11)
              REAL(KIND=4) :: UTCOFFSET
            END SUBROUTINE INPUTMAXNCFILES
          END INTERFACE 
        END MODULE INPUTMAXNCFILES__genmod
