        !COMPILER-GENERATED INTERFACE MODULE: Mon Oct 08 18:57:05 2012
        MODULE INPUTFILES__genmod
          INTERFACE 
            SUBROUTINE INPUTFILES(INPUTCON,MAXNUMOFFILE,ISINPUTFROMNC,  &
     &NUMNCFILES,INPUTTSFILENAME,NCDFCONTAINER,MODELSTARTDATE,          &
     &MODELSTARTHOUR,MODELENDDATE,MODELENDHOUR,MODELDT,                 &
     &NCFILENUMTIMESTEPS,NREFYR,NREFMO,NREFDAY,VARNAMEINNCDF,ARRAYX,    &
     &NOOFTS,INPVALS)
              INTEGER(KIND=4) :: MAXNUMOFFILE
              CHARACTER(LEN=200) :: INPUTCON
              INTEGER(KIND=4) :: ISINPUTFROMNC(11)
              INTEGER(KIND=4) :: NUMNCFILES(11)
              CHARACTER(LEN=200) :: INPUTTSFILENAME(11)
              CHARACTER(LEN=200) :: NCDFCONTAINER(MAXNUMOFFILE,11)
              INTEGER(KIND=4) :: MODELSTARTDATE(3)
              REAL(KIND=4) :: MODELSTARTHOUR
              INTEGER(KIND=4) :: MODELENDDATE(3)
              REAL(KIND=4) :: MODELENDHOUR
              REAL(KIND=4) :: MODELDT
              INTEGER(KIND=4) :: NCFILENUMTIMESTEPS(MAXNUMOFFILE,11)
              INTEGER(KIND=4) :: NREFYR
              INTEGER(KIND=4) :: NREFMO
              INTEGER(KIND=4) :: NREFDAY
              CHARACTER(LEN=50) :: VARNAMEINNCDF(11)
              INTEGER(KIND=4) :: ARRAYX
              INTEGER(KIND=4) :: NOOFTS(11)
              REAL(KIND=4) :: INPVALS(11)
            END SUBROUTINE INPUTFILES
          END INTERFACE 
        END MODULE INPUTFILES__genmod
