        !COMPILER-GENERATED INTERFACE MODULE: Tue Oct 09 13:10:38 2012
        MODULE INPUTVARIABLEVALUE__genmod
          INTERFACE 
            SUBROUTINE INPUTVARIABLEVALUE(INPUTVARNAME,ISINPUTFROMNC,   &
     &NOOFTS,TSV,ALLVALUES,ARRAYX,MODELENDDATE,MODELSTARTDATE,          &
     &MODELSTARTHOUR,MODELENDHOUR,NREFYR,NREFMO,NREFDAY,YEAR,MONTH,DAY, &
     &HOUR,MODELDT,INPVALS,CURRENTARRAYPOS,CURRENTMODELDT,ISTEP)
              INTEGER(KIND=4) :: ARRAYX
              CHARACTER(LEN=200) :: INPUTVARNAME(11)
              INTEGER(KIND=4) :: ISINPUTFROMNC(11)
              INTEGER(KIND=4) :: NOOFTS(11)
              REAL(KIND=8) :: TSV(ARRAYX,11)
              REAL(KIND=4) :: ALLVALUES(ARRAYX,11)
              INTEGER(KIND=4) :: MODELENDDATE(3)
              INTEGER(KIND=4) :: MODELSTARTDATE(3)
              REAL(KIND=4) :: MODELSTARTHOUR
              REAL(KIND=4) :: MODELENDHOUR
              INTEGER(KIND=4) :: NREFYR
              INTEGER(KIND=4) :: NREFMO
              INTEGER(KIND=4) :: NREFDAY
              INTEGER(KIND=4) :: YEAR
              INTEGER(KIND=4) :: MONTH
              INTEGER(KIND=4) :: DAY
              REAL(KIND=4) :: HOUR
              REAL(KIND=4) :: MODELDT
              REAL(KIND=4) :: INPVALS(11)
              INTEGER(KIND=4) :: CURRENTARRAYPOS(11)
              REAL(KIND=8) :: CURRENTMODELDT
              INTEGER(KIND=4) :: ISTEP
            END SUBROUTINE INPUTVARIABLEVALUE
          END INTERFACE 
        END MODULE INPUTVARIABLEVALUE__genmod
