        !COMPILER-GENERATED INTERFACE MODULE: Mon Oct 08 18:57:07 2012
        MODULE LOWERCASE__genmod
          INTERFACE 
            SUBROUTINE LOWERCASE(STR,LCSTR)
              CHARACTER(*) :: STR
              CHARACTER(LEN=LEN_TRIM(STR)) :: LCSTR
            END SUBROUTINE LOWERCASE
          END INTERFACE 
        END MODULE LOWERCASE__genmod
