        !COMPILER-GENERATED INTERFACE MODULE: Tue Oct 09 13:10:41 2012
        MODULE LOWERCASE__genmod
          INTERFACE 
            SUBROUTINE LOWERCASE(STR,LCSTR)
              CHARACTER(*) :: STR
              CHARACTER(LEN=LEN_TRIM(STR)) :: LCSTR
            END SUBROUTINE LOWERCASE
          END INTERFACE 
        END MODULE LOWERCASE__genmod
