        !COMPILER-GENERATED INTERFACE MODULE: Tue Oct 09 13:10:41 2012
        MODULE NCCHECKS__genmod
          INTERFACE 
            SUBROUTINE NCCHECKS(SVFILE,STATESITEVNAME,WATERSHEDFILE,    &
     &MAXNUMOFFILE,ISINPUTFROMNC,NCDFCONTAINER,NUMNCFILES,TOTALNC,      &
     &ALLNCDFFILE)
              INTEGER(KIND=4) :: TOTALNC
              INTEGER(KIND=4) :: MAXNUMOFFILE
              CHARACTER(LEN=200) :: SVFILE
              CHARACTER(LEN=200) :: STATESITEVNAME(32)
              CHARACTER(LEN=200) :: WATERSHEDFILE
              INTEGER(KIND=4) :: ISINPUTFROMNC(11)
              CHARACTER(LEN=200) :: NCDFCONTAINER(MAXNUMOFFILE,32)
              INTEGER(KIND=4) :: NUMNCFILES(11)
              CHARACTER(LEN=200) :: ALLNCDFFILE(TOTALNC)
            END SUBROUTINE NCCHECKS
          END INTERFACE 
        END MODULE NCCHECKS__genmod
