        !COMPILER-GENERATED INTERFACE MODULE: Tue Oct 09 13:10:41 2012
        MODULE NCDF3DARRAYINFO__genmod
          INTERFACE 
            SUBROUTINE NCDF3DARRAYINFO(FILE_NAME,DIMLEN2,DIMLEN1,DIMLEN3&
     &)
              CHARACTER(LEN=50) :: FILE_NAME
              INTEGER(KIND=4) :: DIMLEN2
              INTEGER(KIND=4) :: DIMLEN1
              INTEGER(KIND=4) :: DIMLEN3
            END SUBROUTINE NCDF3DARRAYINFO
          END INTERFACE 
        END MODULE NCDF3DARRAYINFO__genmod
