        !COMPILER-GENERATED INTERFACE MODULE: Mon Oct 08 18:57:07 2012
        MODULE NCDF2DARRAYINFO2__genmod
          INTERFACE 
            SUBROUTINE NCDF2DARRAYINFO2(FILE_NAME,DIMLEN2,DIMLEN1,      &
     &WATERSHEDVARID)
              CHARACTER(LEN=50) :: FILE_NAME
              INTEGER(KIND=4) :: DIMLEN2
              INTEGER(KIND=4) :: DIMLEN1
              CHARACTER(LEN=50) :: WATERSHEDVARID
            END SUBROUTINE NCDF2DARRAYINFO2
          END INTERFACE 
        END MODULE NCDF2DARRAYINFO2__genmod
