        !COMPILER-GENERATED INTERFACE MODULE: Mon Oct 08 18:57:07 2012
        MODULE NCDF3DTIMEREAD__genmod
          INTERFACE 
            SUBROUTINE NCDF3DTIMEREAD(FILE_NAME,TIME_POS,TIME_VAL,      &
     &NUMTIMESTEP,SYEAR,SMONTH,SDAY)
              CHARACTER(LEN=50) :: FILE_NAME
              INTEGER(KIND=4) :: TIME_POS
              REAL(KIND=8) :: TIME_VAL(1)
              INTEGER(KIND=4) :: NUMTIMESTEP
              INTEGER(KIND=4) :: SYEAR
              INTEGER(KIND=4) :: SMONTH
              INTEGER(KIND=4) :: SDAY
            END SUBROUTINE NCDF3DTIMEREAD
          END INTERFACE 
        END MODULE NCDF3DTIMEREAD__genmod
