        !COMPILER-GENERATED INTERFACE MODULE: Mon Oct 08 18:57:07 2012
        MODULE NCDFREADALLTS__genmod
          INTERFACE 
            SUBROUTINE NCDFREADALLTS(FILE_NAME,VAR_NAME,ALLVAL,IYCOORD, &
     &JXCOORD,REC)
              INTEGER(KIND=4) :: REC
              CHARACTER(LEN=50) :: FILE_NAME
              CHARACTER(LEN=50) :: VAR_NAME
              REAL(KIND=4) :: ALLVAL(REC)
              INTEGER(KIND=4) :: IYCOORD
              INTEGER(KIND=4) :: JXCOORD
            END SUBROUTINE NCDFREADALLTS
          END INTERFACE 
        END MODULE NCDFREADALLTS__genmod
