        !COMPILER-GENERATED INTERFACE MODULE: Mon Oct 08 18:57:07 2012
        MODULE NCDF2DARRAYINFO__genmod
          INTERFACE 
            SUBROUTINE NCDF2DARRAYINFO(FILE_NAME,DIMLEN2,DIMLEN1)
              CHARACTER(LEN=200) :: FILE_NAME
              INTEGER(KIND=4) :: DIMLEN2
              INTEGER(KIND=4) :: DIMLEN1
            END SUBROUTINE NCDF2DARRAYINFO
          END INTERFACE 
        END MODULE NCDF2DARRAYINFO__genmod
