        !COMPILER-GENERATED INTERFACE MODULE: Tue Oct 09 13:10:41 2012
        MODULE NCDF2DREAD__genmod
          INTERFACE 
            SUBROUTINE NCDF2DREAD(FILE_NAME,VARNAME,SINGLEARRAY,I,J)
              CHARACTER(LEN=50) :: FILE_NAME
              CHARACTER(LEN=50) :: VARNAME
              REAL(KIND=4) :: SINGLEARRAY(1)
              INTEGER(KIND=4) :: I
              INTEGER(KIND=4) :: J
            END SUBROUTINE NCDF2DREAD
          END INTERFACE 
        END MODULE NCDF2DREAD__genmod
