        !COMPILER-GENERATED INTERFACE MODULE: Tue Oct 09 13:10:41 2012
        MODULE NETCDFTIMEARRAY__genmod
          INTERFACE 
            SUBROUTINE NETCDFTIMEARRAY(FILE_NAME,TIME_OUT,TIMELENGTH)
              INTEGER(KIND=4) :: TIMELENGTH
              CHARACTER(LEN=50) :: FILE_NAME
              REAL(KIND=8) :: TIME_OUT(TIMELENGTH)
            END SUBROUTINE NETCDFTIMEARRAY
          END INTERFACE 
        END MODULE NETCDFTIMEARRAY__genmod
