        !COMPILER-GENERATED INTERFACE MODULE: Mon Oct 08 18:57:05 2012
        MODULE NUMOUTFILES__genmod
          INTERFACE 
            SUBROUTINE NUMOUTFILES(OUTCONTROLFILE,MODELSTARTDATE,       &
     &MODELSTARTHOUR,MODELENDDATE,MODELENDHOUR,MODELDT,DIMLEN2,DIMLEN1, &
     &NUMTIMESTEP,NUMOFFILE,NUMOUTPOINT,OUTCOUNT)
              CHARACTER(LEN=200) :: OUTCONTROLFILE
              INTEGER(KIND=4) :: MODELSTARTDATE(3)
              REAL(KIND=4) :: MODELSTARTHOUR
              INTEGER(KIND=4) :: MODELENDDATE(3)
              REAL(KIND=4) :: MODELENDHOUR
              REAL(KIND=4) :: MODELDT
              INTEGER(KIND=4) :: DIMLEN2
              INTEGER(KIND=4) :: DIMLEN1
              INTEGER(KIND=4) :: NUMTIMESTEP
              INTEGER(KIND=4) :: NUMOFFILE
              INTEGER(KIND=4) :: NUMOUTPOINT
              INTEGER(KIND=4) :: OUTCOUNT
            END SUBROUTINE NUMOUTFILES
          END INTERFACE 
        END MODULE NUMOUTFILES__genmod
