        !COMPILER-GENERATED INTERFACE MODULE: Mon Oct 08 18:57:07 2012
        MODULE OUTPUTTIMENETCDF__genmod
          INTERFACE 
            SUBROUTINE OUTPUTTIMENETCDF(NCIDARRAY,OUTVAR,NUMTIMESTEP,   &
     &OUTCOUNT,INCFILE,IOUTV,NUMTIMESTEPPERFILE,NUMOFFILE,STARTENDNCDF, &
     &FNDJDT,JXCOORD,IYCOORD)
              INTEGER(KIND=4) :: NUMOFFILE
              INTEGER(KIND=4) :: OUTCOUNT
              INTEGER(KIND=4) :: NUMTIMESTEP
              INTEGER(KIND=4) :: NCIDARRAY(NUMOFFILE,OUTCOUNT)
              INTEGER(KIND=4) :: OUTVAR(OUTCOUNT)
              INTEGER(KIND=4) :: INCFILE
              INTEGER(KIND=4) :: IOUTV
              INTEGER(KIND=4) :: NUMTIMESTEPPERFILE(NUMOFFILE)
              INTEGER(KIND=4) :: STARTENDNCDF(NUMOFFILE,2)
              REAL(KIND=8) :: FNDJDT(NUMTIMESTEP)
              INTEGER(KIND=4) :: JXCOORD
              INTEGER(KIND=4) :: IYCOORD
            END SUBROUTINE OUTPUTTIMENETCDF
          END INTERFACE 
        END MODULE OUTPUTTIMENETCDF__genmod
