        !COMPILER-GENERATED INTERFACE MODULE: Mon Oct 08 18:57:05 2012
        MODULE TIMESERIESANDTIMESTEPS__genmod
          INTERFACE 
            SUBROUTINE TIMESERIESANDTIMESTEPS(MAXNUMOFFILE,NUMNCFILES,  &
     &ISINPUTFROMNC,INPUTTSFILENAME,NCDFCONTAINER,MODELSTARTDATE,       &
     &MODELSTARTHOUR,MODELENDDATE,MODELENDHOUR,MODELDT,                 &
     &NCFILENUMTIMESTEPS,VARNAMEINNCDF,ARRAYX,NOOFTS,TSV,ALLVALUES)
              INTEGER(KIND=4) :: ARRAYX
              INTEGER(KIND=4) :: MAXNUMOFFILE
              INTEGER(KIND=4) :: NUMNCFILES(11)
              INTEGER(KIND=4) :: ISINPUTFROMNC(11)
              CHARACTER(LEN=200) :: INPUTTSFILENAME(11)
              CHARACTER(LEN=200) :: NCDFCONTAINER(MAXNUMOFFILE,11)
              INTEGER(KIND=4) :: MODELSTARTDATE(3)
              REAL(KIND=4) :: MODELSTARTHOUR
              INTEGER(KIND=4) :: MODELENDDATE(3)
              REAL(KIND=4) :: MODELENDHOUR
              REAL(KIND=4) :: MODELDT
              INTEGER(KIND=4) :: NCFILENUMTIMESTEPS(MAXNUMOFFILE,11)
              CHARACTER(LEN=50) :: VARNAMEINNCDF(11)
              INTEGER(KIND=4) :: NOOFTS(11)
              REAL(KIND=8) :: TSV(ARRAYX,11)
              REAL(KIND=4) :: ALLVALUES(ARRAYX,11)
            END SUBROUTINE TIMESERIESANDTIMESTEPS
          END INTERFACE 
        END MODULE TIMESERIESANDTIMESTEPS__genmod
