        !COMPILER-GENERATED INTERFACE MODULE: Mon Oct 08 18:57:05 2012
        MODULE VALUES4VAREACHGRID__genmod
          INTERFACE 
            SUBROUTINE VALUES4VAREACHGRID(ISINPUTFROMNC,MAXNUMOFFILE,   &
     &NUMNCFILES,NCDFCONTAINER,VARNAMEINNCDF,IYCOORD,JXCOORD,           &
     &NCFILENUMTIMESTEPS,NOOFTS,ARRAYX,TSV,ALLVALUES)
              INTEGER(KIND=4) :: ARRAYX
              INTEGER(KIND=4) :: MAXNUMOFFILE
              INTEGER(KIND=4) :: ISINPUTFROMNC(11)
              INTEGER(KIND=4) :: NUMNCFILES(11)
              CHARACTER(LEN=200) :: NCDFCONTAINER(MAXNUMOFFILE,11)
              CHARACTER(LEN=50) :: VARNAMEINNCDF(11)
              INTEGER(KIND=4) :: IYCOORD
              INTEGER(KIND=4) :: JXCOORD
              INTEGER(KIND=4) :: NCFILENUMTIMESTEPS(MAXNUMOFFILE,11)
              INTEGER(KIND=4) :: NOOFTS(11)
              REAL(KIND=8) :: TSV(ARRAYX,11)
              REAL(KIND=4) :: ALLVALUES(ARRAYX,11)
            END SUBROUTINE VALUES4VAREACHGRID
          END INTERFACE 
        END MODULE VALUES4VAREACHGRID__genmod
