        !COMPILER-GENERATED INTERFACE MODULE: Mon Oct 08 18:57:06 2012
        MODULE WSUNIQUEARRAY__genmod
          INTERFACE 
            SUBROUTINE WSUNIQUEARRAY(WATERSHEDFILE,WATERSHEDVARID,      &
     &DIMLEN1,DIMLEN2,UNIQUEIDNUMBER,UNIQUEIDARRAY)
              INTEGER(KIND=4) :: UNIQUEIDNUMBER
              CHARACTER(LEN=200) :: WATERSHEDFILE
              CHARACTER(LEN=200) :: WATERSHEDVARID
              INTEGER(KIND=4) :: DIMLEN1
              INTEGER(KIND=4) :: DIMLEN2
              INTEGER(KIND=4) :: UNIQUEIDARRAY(UNIQUEIDNUMBER)
            END SUBROUTINE WSUNIQUEARRAY
          END INTERFACE 
        END MODULE WSUNIQUEARRAY__genmod
